/**
 * Post-processing of `prisma db pull` over the schema generated by Strapi.
 *
 * Strapi creates indexes with the same name as the foreign key (`*_fk`, `*_ifk`),
 * and Prisma requires unique names per model across PKs/indexes/FKs. We rename the
 * `map` of the affected `@@index` entries with an `_idx` suffix. It only affects
 * migration metadata (we never run `prisma migrate` against this DB: the schema is
 * managed by Strapi until phase 5).
 *
 * Usage: npm run prisma:pull (chains db pull + this script + generate)
 */
const fs = require("fs");
const path = require("path");

const schemaPath = path.join(__dirname, "schema.prisma");
const schema = fs.readFileSync(schemaPath, "utf8");

let renamed = 0;
const fixed = schema.replace(
  /(@@index\(\[[^\]]*\], map: ")([^"]*_i?fk)(")/g,
  (_, pre, name, post) => {
    renamed += 1;
    return `${pre}${name}_idx${post}`;
  },
);

fs.writeFileSync(schemaPath, fixed);
console.log(`fix-schema: ${renamed} indexes renamed with the _idx suffix`);
